### PR TITLE
Add option to use custom log file

### LINKED ISSUE #1113: Add CLI flag to change location of the log file
**Describe the Feature**
Tern currently creates a `tern.log` file in the directory wherever the Tern command is run that captures the terminal output during a run. Add a CLI flag that could change the location of where the log file ends up.

**Use Cases**
When running Tern with minikube, it would be to direct the log file to the mount directory instead of leaving it in the container.

**Implementation Changes**
Add a CLI flag that enables the user to specify a location. If no location is provided, leave the log file in its current directory.

### PR DESCRIPTION
**Pull request by nishakm**
Some situations require the log files to be written to a different
location than the current working directory. This commit introduces
the option `-l/--log-file` to provide a different file path. To
use this option, run:

tern -l path/to/log/file

In order to enable this functionality, some global logging
variables were moved to the do_main function.

Fixes #1113

Signed-off-by: Nisha K <nishak@vmware.com>

### CODE REVIEW

**Comment by rnjudge** [comment]
This looks good. My only thought would be: do we want this functionality to write to a specific file or instead, a directory? Right now the file has to exist.. which is kinda funky since someone would just have to create an empty file... Do we want this to just create the `log.txt` file in the directory specified?

**Comment by nishakm** [comment]
> This looks good. My only thought would be: do we want this functionality to write to a specific file or instead, a directory? Right now the file has to exist.. which is kinda funky since someone would just have to create an empty file... Do we want this to just create the `log.txt` file in the directory specified? Alternatively, we could create the path/file if it doesn't exist.

Turns out, logging creates a file if it doesn't exist in the specific path. I could provide a check for the directory existing, and if it doesn't exit gracefully.

**Comment by nishakm** [comment]
> > > This looks good. My only thought would be: do we want this functionality to write to a specific file or instead, a directory? Right now the file has to exist.. which is kinda funky since someone would just have to create an empty file... Do we want this to just create the `log.txt` file in the directory specified? Alternatively, we could create the path/file if it doesn't exist.
> > 
> > 
> > Turns out, logging creates a file if it doesn't exist in the specific path. I could provide a check for the directory existing, and if it doesn't exit gracefully.
> 
> In my testing, it failed even if the directory existed but the file did not..
> 
> ```
> rjudge:tern$ tern report -i debian:buster -l test.txt
> usage: Tern report [-h] [-d DOCKERFILE] [-i IMAGE] [-w FILE] [-y [LAYER_NUMBER]]
>                    [-li] [-x EXTENSION] [-f REPORT_FORMAT] [-o FILE] [-l PATH]
>                    [-ctx FILES [FILES ...]]
> Tern report: error: argument -l/--live: test.txt: does not exist
> ```
> 
> Are you expecting a file or a directory path with the `-l` option?

Doh!

Supposed to be `tern -l test.txt report -i debian:buster`

Perhaps I should give it a different flag name?

**Comment by nishakm** [comment]
@rnjudge Looks good?
```
$ tern -l /some/path/log report -i debian:buster                                                                                        
usage: Tern [-h] [-q] [-l FILE] [-c] [-k] [-r] [-wd PATH] [-dr DRIVER_OPTION] [-v] {report,lock,debug} ...                                                                                    
Tern: error: argument -l/--log-file: directory path /some/path does not exist                                                                                                                 
(terndev) nisha@ubuntu ~/terndev/tern (1113-log-file) $ tern -l ~/tern.log report -i debian:buster                                                                                            
2022-02-07 11:25:38,163 - DEBUG - __main__ - Starting...                                                                                                                                      
2022-02-07 11:25:38,163 - DEBUG - prep - Setting up...                                                                                                                                        
2022-02-07 11:25:47,021 - DEBUG - rootfs - Running command: sudo chmod +x /home/nisha/terndev/tern/tern/tools/fs_hash.sh 

$ cat ~/tern.log
2022-02-07 11:25:38,163 - DEBUG - __main__ - Starting...
2022-02-07 11:25:38,163 - DEBUG - prep - Setting up...
2022-02-07 11:25:47,021 - DEBUG - rootfs - Running command: sudo chmod +x /home/nisha/terndev/tern/tern/tools/fs_hash.sh  
```

**Comment by rnjudge** [comment]
Looks great @nishakm. My last nit/question is that the CLI hint for this says "Provide a custom file to write logs to" -- Do we want to change `file` to `directory`? or is it acceptable to provide a log file name? If a log file name is accepted maybe we want to say `file or directory`?

**Comment by rnjudge** [comment]
> > Looks great @nishakm. My last nit/question is that the CLI hint for this says "Provide a custom file to write logs to" -- Do we want to change `file` to `directory`? or is it acceptable to provide a log file name? If a log file name is accepted maybe we want to say `file or directory`?
> 
> It should be a `FILE` NOT a directory. So you can provide `file` or `path/to/file` and `file` will be the log file. Can you suggest a way I can make that clearer?

@nishakm It is clear in the directions I was just confused by your earlier comment `Turns out, logging creates a file if it doesn't exist in the specific path. I could provide a check for the directory existing, and if it doesn't exit gracefully.`

If a file is expected I will merge this.

**Pull request merged**
