### PR TITLE
Update release_tests.py

### LINKED ISSUE #996: Implement running of functional tests in python
**Description**
This task is contingent on merging task #995 into main. Now that we have a list of tests to invoke, we will implement invoking them. 

**To Do**
1. Modify the file `ci/release_tests.py` to invoke each of the tests in the list `tests`.
```
import subprocess  # nosec

tests = [...] <-- changes to be included in #995 

for t in tests:
    subprocess.check_output(t, shell=True)  # nosec
```
2. Submit these changes in a PR

**Super Issues**
#885

### PR DESCRIPTION
**Pull request by trangttdang**
This commit modifies release_tests.py to invoke each of the tests in the list of tests.

Resolves #996

Signed-off-by: Trang Dang trangttdang01@gmail.com

### CODE REVIEW

**Comment by nishakm** [comment]
@trangttdang can you update your commit message such that it has a body and a `Signed-off-by` like your previous commit?

**Review by trangttdang — COMMENTED** [review]
This commit modifies release_tests.py to invoke each of the tests in the list of tests.

Resolves #996

Signed-off-by: Trang Dang trangttdang01@gmail.com

**Comment by nishakm** [comment]
> This commit modifies release_tests.py to invoke each of the tests in the list of tests.
> 
> Resolves #996
> 
> Signed-off-by: Trang Dang [trangttdang01@gmail.com](mailto:trangttdang01@gmail.com)

Do `git commit --amend` and then update the commit message with this:
```
Update release_tests.py

This commit modifies release_tests.py to invoke each of the tests
in the list of tests.

Resolves #996

Signed-off-by: Trang Dang <trangttdang01@gmail.com>
```

Then `git push -f origin <your dev branch>`

**Comment by rnjudge** [comment]
Closing this as #1017 was opened to replace it.

**Pull request closed without merging**
