### PR TITLE
 Update release_tests.py

### LINKED ISSUE #996: Implement running of functional tests in python
**Description**
This task is contingent on merging task #995 into main. Now that we have a list of tests to invoke, we will implement invoking them. 

**To Do**
1. Modify the file `ci/release_tests.py` to invoke each of the tests in the list `tests`.
```
import subprocess  # nosec

tests = [...] <-- changes to be included in #995 

for t in tests:
    subprocess.check_output(t, shell=True)  # nosec
```
2. Submit these changes in a PR

**Super Issues**
#885

### PR DESCRIPTION
**Pull request by trangttdang**
Update release_tests.py

This commit modifies release_tests.py to invoke each of tests in test list

Resolves #996

Signed-off-by: Trang Dang <trangttdang01@gmail.com>

### CODE REVIEW

**Comment by rnjudge** [comment]
Hi @trangttdang, Looks like this PR still has an extra commit attached to it -- do you need help getting rid of that?

**Comment by trangttdang** [comment]
Yes, could you get rid of that? Thank you so much.

**Comment by nishakm** [comment]
@trangttdang Would you be open to redo-ing this PR? I recommend setting up your fork of tern in this way: https://github.com/nishakm/puns#how-to-submit-prs-with-your-github-fork. Don't forget to configure your git first! https://github.com/nishakm/puns#how-to-configure-your-git. When you commit your changes, run `git commit -s` and your <Signed-off-by> will automatically appear in your message!

**Comment by trangttdang** [comment]
> @trangttdang Would you be open to redo-ing this PR? I recommend setting up your fork of tern in this way: https://github.com/nishakm/puns#how-to-submit-prs-with-your-github-fork. Don't forget to configure your git first! https://github.com/nishakm/puns#how-to-configure-your-git. When you commit your changes, run `git commit -s` and your will automatically appear in your message!

Hi @nishakm Thank you for your help. I have a problem when trying to push my changes, it says permission denied [https://drive.google.com/file/d/16QhsnBD1wnE5e-6oNd7J3-eu1imAP_5N/view?usp=sharing](url). Could you check it for me? Thank you!

**Pull request closed without merging**
