### PR TITLE
Fix linting error for generator.py

### LINKED ISSUE #648: Fix "too-many-branches" prospector error for tern/formats/default/generator.py
**Description**
Fix "too-many-branches" prospector error for tern/formats/default/generator.py

**To Do**
After code changes, run `prospector` (not `prospector tern/formats/default/generator.py`). No errors for this file should be present.

**Super Issues**
#517

### PR DESCRIPTION
**Pull request by ForgetMe17**
Add a new function get_layer_info_list() to replace the deeper branches.

Fixes #648.
Signed-off-by: WangJL <hazard15020@gmail.com>

### CODE REVIEW

**Comment by nishakm** [comment]
@ForgetMe17 small request to modify your commit message:
```
Work towards #648 -> Fixes #648 
```
Thanks so much!

**Comment by rnjudge** [comment]
The changes look good. Slightly confused on the commit message "`remove unused variable layer_file_licenses_list in the origin function print_full_report(image).`" since the `layer_file_licenses_list` variable is not actually removed and not unused? From what I can tell, it is just moved to a new function but still used?

**Comment by ForgetMe17** [comment]
Yes! @rnjudge .In the origin code `layer_file_licenses_list` is an intermediate variables. We join the elements in the `layer_file_licenses_list` to get `file_level_licenses`. 
I move `layer_file_licenses_list`  to a new function and not return this variable. So it is like kind of removing this variable in the function `print_full_report(image)`.

**Comment by rnjudge** [comment]
> Yes! @rnjudge .In the origin code `layer_file_licenses_list` is an intermediate variables. We join the elements in the `layer_file_licenses_list` to get `file_level_licenses`.
> I move `layer_file_licenses_list` to a new function and not return this variable. So it is like kind of removing this variable in the function `print_full_report(image)`.

Yes, I understand what the PR is doing :) The wording is just a little confusing and I don't think helps summarize the purpose of this PR.. Can you delete  `Remove unused variable layer_file_licenses_list in the origin function print_full_report(image).` from your commit message? Otherwise this looks good. Thank you!

**Comment by ForgetMe17** [comment]
Yes!

**Pull request merged**
