### PR TITLE
Minimize complexity of do_main

### PR DESCRIPTION
**Pull request by nishakm**
- Use the "dest" option in adding subparsers, so we have a
  persistent variable to compare subcommand names to. This gets
  rid of one if-then loop.
- Move the check for the Docker image input type to a separate
  function, removing two more if checks from do_main.

Signed-off-by: Nisha K <nishak@vmware.com>

### CODE REVIEW

**Comment by rnjudge** [comment]
@aalexanderr Heads up: this will affect parts of your PR.

**Comment by nishakm** [comment]
@rnjudge I can update this PR if you merge @aalexanderr's PR.

**Comment by nishakm** [comment]
@rnjudge updated the PR. OK to merge?

**Comment by rnjudge** [comment]
> @rnjudge updated the PR. OK to merge?

LGTM!

**Pull request merged**
