### PR TITLE
Mixup of lines in image_layer.py

### LINKED ISSUE #1069: There is a mixup of lines in the documentation of `image_layer.py`
I think the lines in the following documentation are somehow not in correct order. Maybe chunks were added between multi line statements. Especially `import_str:` is broken.

https://github.com/tern-tools/tern/blob/a3e76cdb0e08d92e896822634cbcf670bdd05e30/tern/classes/image_layer.py#L18-L43

### PR DESCRIPTION
**Pull request by sayantani11**
There was  a mismatched line in
the property descriptions.

Fixes #1069

Signed-off by: Sayantani Saha <ii.sayantani.ii@gmail.com>

### CODE REVIEW

**Comment by rnjudge** [comment]
Hi @sayantani11 -- Thanks for the PR! Note that this PR needs the line in question moved, not removed. See the suggestion [here](https://github.com/rnjudge/tern/pull/9/files#diff-7c77af6176f4142ab80d4e4b2d0b2973a3d45de2095d3deb691849e756fc981bR31-R35 ) for what needs to be done in tern/classes/image_layer.py.

**Comment by rnjudge** [comment]
Hi @sayantani11 are you still interested in taking this on?

**Comment by sayantani11** [comment]
Yes @rnjudge I didn't get the time to fix this, I'll do as soon as possible

**Comment by rnjudge** [comment]
Closing this PR for now. Feel free to re-open when you have time to update :)

**Pull request closed without merging**
