### PR TITLE
Added copyright info for NPM packages

### PR DESCRIPTION
**Pull request by mzachar**
Implementation for feature #957

### CODE REVIEW

**Comment by nishakm** [comment]
@mzachar Could you explain in your commit message body what the changes are and what they do? Use `git commit --amend` and `git push -f` to mzachar:main

**Comment by rnjudge** [comment]
@mzachar Thanks for updating! Just a few more small nits -- could you make sure that your commit message conforms to the [commit message format requirements](https://github.com/tern-tools/tern/blob/main/CONTRIBUTING.md#commit-message-format)? Namely, I think you just need to add a `Signed-off-by` line, wrap the line lengths at 72 characters (50 chars for the title) and please change "Implements" to "Resolves" so github will close the issue once we merge :) 

Thanks again for contributing to Tern! We appreciate it and I look forward to merging this!

**Comment by mzachar** [comment]
@rnjudge No worries, hopefully I did not forget anything and sorry for not reading the requirements in the first place :)

**Comment by nishakm** [comment]
@mzachar 😅 More commit message formatting issues. Just make your commit message in this way:
```
Added copyright info for NPM packages

Copyrights are extracted by checking if common licensing file names
exists in the package and if they are found the content is then
returned.

As the scanning is split between container and host (due to the jq
tool availability) the package path is left trimmed to remove first
'/' - effectively converting it to relative path which can then be
resolved correctly from the current working directory of host
command.

More license files to check can be added in the future by extending
the "files" variable

Resolves: #958

Signed-off-by: mzachar <mzachar@users.noreply.github.com>
```
One request: We require a reachable email address in the DCO (Signed-off-by). You can set this in your git config by following [these instructions](https://github.com/nishakm/puns#how-to-configure-your-git) and then do `git commit -s --amend`

**Review by rnjudge — APPROVED** [review]
Tested and copyrights are available in the more verbose reports.

**Pull request merged**
