### PR TITLE
Implement tests in release_tests.py

### PR DESCRIPTION
**Pull request by alannaemmrie**
Added implementation to release_tests.py to run all tests in the included test suite. Calling ./release_tests.py will now run all the tests in the file via subprocess.run and display passed/failed tests as well as captured output.

Resolves: #996
Signed-off-by: Alanna Hill aehill@umich.edu

### CODE REVIEW

**Comment by alannaemmrie** [comment]
Hi, I made this pull request a few hours ago and got an email about failing a check.  I looked at it further and it was because one of the commits that I made had a commit message without a body. I just went back and amended the commit message and added a body, which hopefully should let it pass the commit message linting check now!

**Comment by alannaemmrie** [comment]
Hoping third time is the charm on the commit message formatting! They are passing locally so fingers crossed.

**Comment by rnjudge** [comment]
Thanks again @alannaemmrie for this PR. I think you may have attached an extra set of commits to it when you updated? If you need help let me know.

**Comment by rnjudge** [comment]
This hasn't gotten attention in quite a while. Closing for now.

**Pull request closed without merging**
