### PR TITLE
Enable npm and yarn package listing

### PR DESCRIPTION
**Pull request by rnjudge**
This PR adds scripts in command_lib/base.yml and snippets.yml
to list the packages installed by npm and yarn.

Works towards #609

Signed-off-by: Rose Judge <rjudge@vmware.com>
Signed-off-by: abhay <abhay.katheria1998@gmail.com>
Signed-off-by: Nisha K <nishak@vmware.com>

### CODE REVIEW

**Comment by rnjudge** [comment]
I am finding an error when running with these changes using an image built from the following Dockerfile:

```
FROM node:12-alpine3.11

RUN npm install is-npm
```

```
2020-04-30 09:46:14,343 - DEBUG - rootfs - Running command: sudo unshare -pf --mount-proc=/home/rjudge/.tern/temp/mergedir/proc chroot /home/rjudge/.tern/temp/mergedir /bin/sh -c pkgs=`npm list -g | grep -v "duped" | grep -v "/usr/*"| cut -f2 -d'+' | cut -f1 -d'@' | cut -f2 -d'``' | cut -f2 -d' '` && for p in $pkgs; do npm view $p | head -2 | tail -1 | cut -f1 -d'|' | cut -f2 -d'@'; done
2020-04-30 09:46:14,365 - ERROR - rootfs - Command failed. /bin/sh: syntax error: unterminated quoted string

2020-04-30 09:46:14,365 - WARNING - rootfs - Error executing command in chroot
```

My haunch is this has to do with the single backtick character used to collect package names in `base.yml` as the command itself is not an issue if I am working in a running container command line (like mongo-express:latest`. Also note that I get this error 3 times when trying to collect `versions`, `licenses` and `proj_urls`.

**Comment by nishakm** [comment]
This worked for me, although the `versions` collection took quite a long time.
```
  names:
    invoke:
      1:
        container:
          - "npm list -g | sed 's/\\(^[^a-z]*\\)\\([_.a-z0-9-]*\\)\\(@.*\\)/\\2/g' | grep -v '/usr*' | uniq"
    delimiter: "\n"
  versions:
    invoke:
      1:
        container:
          - "pkgs=`npm list -g | sed 's/\\(^[^a-z]*\\)\\([_.a-z0-9-]*\\)\\(@.*\\)/\\2/g' | grep -v '/usr*' | uniq`"
          - "for p in $pkgs; do npm view $p | head -2 | tail -1 | cut -f1 -d'|' | cut -f2 -d'@'; done"
    delimiter: "\n"
```

**Comment by rnjudge** [comment]
I updated my commit to reflect suggestions from Nisha (thanks!) as well as some additional tweaks. However, it seems that when I run with these changes I can only get EITHER versions to print correctly OR the versions of the packages to print correctly. I know that the commands are correct because when I use the `verify_invoke` script to print the `names`, `licenses` and `versions`, I get the correct output with the correct number of elements. The issue seems to be when running it in a container.

The issues are the same when either licenses are printed or versions are. I think it depends which gets invoked first from base.yml.
```
error: npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning ENETUNREACH: request to https://registry.npmjs.org/string_decoder failed, reason: connect ENETUNREACH 2606:4700::6810:1523:443 - Local (:::0)
npm WARN registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EAI_AGAIN: request to https://registry.npmjs.org/safe-buffer failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org
npm WARN registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.
```

**Comment by nishakm** [comment]
It worked for me:

```
        File licenses found in Layer:  None
        Packages found in Layer:  npm-6.14.5, abbrev-1.1.1, ansicolors-0.3.2, ansistyles-0.1.3, aproba-2.0.0, archy-1.0.0, bin-links-2.1.2, bluebird-3.7.2, cmd-shim-4.0.1, gentle-fs-2.3.1, graceful-fs-4.2.4, npm-normalize-package-bin-1.0.1, write-file-atomic-3.0.3, byte-size-6.2.0, cacache-15.0.3, chownr-2.0.0, figgy-pudding-3.5.2, glob-7.1.6, infer-owner-1.0.4, lru-cache-5.1.1, mississippi-4.0.0, mkdirp-1.0.4, move-concurrently-1.0.1, promise-inflight-1.0.1, rimraf-3.0.2, ssri-8.0.0, unique-filename-1.1.1, y18n-4.0.0, call-limit-1.1.1, ci-info-2.0.0, cli-columns-3.1.2, string-width-4.2.0, is-fullwidth-code-point-3.0.0, strip-ansi-6.0.0, ansi-regex-5.0.0, cli-table3-0.6.0, colors-1.4.0, object-assign-4.1.1, columnify-1.5.4, wcwidth-1.0.1, defaults-1.0.3, clone-2.1.2, config-chain-1.1.12, ini-1.3.5, proto-list-1.2.4, debuglog-1.0.1, detect-indent-6.0.0, detect-newline-3.1.0, dezalgo-1.0.3, asap-2.0.6, wrappy-1.0.2, editor-1.0.0, find-npm-prefix-1.0.2, fs-vacuum-1.2.10, path-is-inside-1.0.2, fs-write-stream-atomic-1.0.10, iferr-1.0.2, imurmurhash-0.1.4, readable-stream-3.6.0, core-util-is-1.0.2, inherits-2.0.4, isarray-2.0.5, process-nextick-args-2.0.1, safe-buffer-5.2.1, string_decoder-1.3.0, util-deprecate-1.0.2, read-cmd-shim-2.0.0, slide-1.1.6, fs.realpath-1.0.0, inflight-1.0.6, minimatch-3.0.4, brace-expansion-1.1.11, balanced-match-1.0.0, concat-map-0.0.1, once-1.4.0, path-is-absolute-2.0.0, has-unicode-2.0.1, hosted-git-info-3.0.4, init-package-json-1.10.3, npm-package-arg-8.0.1, promzard-0.3.0, read-1.0.7, read-package-json-2.1.1, semver-7.3.2, validate-npm-package-license-3.0.4, validate-npm-package-name-3.0.0, is-cidr-4.0.0, cidr-regex-3.0.0, ip-regex-4.1.0, json-parse-better-errors-1.0.2, tream-0.1.4, jsonparse-1.3.1, through-2.3.8, lazy-property-1.0.0, libcipm-4.0.8, lock-verify-2.2.0, npm-lifecycle-3.1.5, npm-logical-tree-1.2.1, pacote-11.1.10, worker-farm-1.7.0, libnpm-3.0.1, libnpmaccess-4.0.0, libnpmconfig-1.2.1, find-up-4.1.0, locate-path-5.0.0, p-locate-4.1.0, p-limit-2.3.0, p-try-2.2.0, path-exists-4.0.0, libnpmhook-6.0.0, libnpmorg-2.0.0, libnpmpublish-3.0.1, get-stream-5.1.0, lodash.clonedeep-4.5.0, normalize-package-data-2.5.0, npm-registry-fetch-8.0.3, libnpmsearch-3.0.0, libnpmteam-2.0.1,
npm-profile-5.0.1, npmlog-4.1.2, stringify-package-1.0.1, pump-3.0.0, libnpx-10.2.3, dotenv-8.2.0, update-notifier-4.1.0, which-2.0.2, yargs-15.3.1, cliui-6.0.0, wrap-ansi-7.0.0, code-point-at-1.1.0, decamelize-4.0.0, get-caller-file-2.0.5, os-locale-5.0.0, execa-4.0.1, cross-spawn-7.0.2, nice-try-2.0.1, path-key-3.1.1, shebang-command-2.0.0, shebang-regex-3.0.0, is-stream-2.0.0, npm-run-path-4.0.1, p-finally-2.0.1, signal-exit-3.0.3, strip-eof-2.0.0, lcid-3.1.1, invert-kv-3.0.1, mem-6.1.0, map-age-cleaner-0.1.3, p-defer-3.0.0, mimic-fn-3.0.0, p-is-promise-3.0.0, require-directory-2.1.1, require-main-filename-2.0.0, set-blocking-2.0.0, which-module-2.0.0, yargs-parser-18.1.3, camelcase-6.0.0, lockfile-1.0.4, lodash._baseindexof-3.1.0, lodash._baseuniq-4.6.0, lodash._createset-4.0.3, lodash._root-3.0.1, lodash._bindcallback-3.0.1, lodash._cacheindexof-3.0.2, lodash._createcache-3.1.2, lodash._getnative-3.9.1, lodash.restparam-3.6.1, lodash.union-4.6.0, lodash.uniq-4.5.0, lodash.without-4.4.0, yallist-4.0.0, meant-1.0.1, concat-stream-2.0.0, buffer-from-1.1.1, typedarray-0.0.6, duplexify-4.1.1, end-of-stream-1.4.4, stream-shift-1.0.1, flush-write-stream-2.0.0, from2-2.3.0, parallel-transform-1.2.0, cyclist-1.0.1, pumpify-2.0.1, stream-each-1.2.3, through2-3.0.1, xtend-4.0.2, minimist-1.2.5, copy-concurrently-1.0.5, run-queue-2.0.1, node-gyp-6.1.0, env-paths-2.2.0, nopt-4.0.3, request-2.88.2, tar-6.0.2, osenv-0.1.5, resolve-1.17.0, path-parse-1.0.6, npm-audit-report-2.1.1, console-control-strings-1.1.0, npm-cache-filename-1.0.2, npm-install-checks-4.0.0, byline-5.0.0, resolve-from-5.0.0, uid-number-0.0.6, umask-1.1.0, npm-packlist-2.1.2, ignore-walk-3.0.3, npm-bundled-1.1.1, npm-pick-manifest-6.1.0, make-fetch-happen-8.0.7, agentkeepalive-4.1.2, humanize-ms-1.2.1, ms-2.1.2, http-cache-semantics-4.1.0, http-proxy-agent-4.0.1, agent-base-6.0.0, es6-promisify-6.1.1, es6-promise-4.2.8, debug-4.1.1, https-proxy-agent-5.0.0, node-fetch-npm-2.0.4, encoding-0.1.12, iconv-lite-0.5.1, safer-buffer-2.1.2, promise-retry-1.1.1, socks-proxy-agent-5.0.0, socks-2.3.3, ip-1.1.5, smart-buffer-4.1.0, npm-user-validate-1.0.0, are-we-there-yet-1.1.5, delegates-1.0.0, gauge-3.0.0, number-is-nan-2.0.0, wide-align-1.1.3, opener-1.5.1, os-homedir-2.0.0, os-tmpdir-2.0.0, minipass-3.1.3, err-code-2.0.0, retry-0.12.0, protoduck-5.0.1, genfun-5.0.0, qrcode-terminal-0.12.0, query-string-6.12.1, decode-uri-component-0.2.0, split-on-first-2.0.0, strict-uri-encode-2.0.0, qw-1.0.1, mute-stream-0.0.8, read-installed-4.0.3, readdir-scoped-modules-1.1.0, util-extend-1.0.3, read-package-tree-5.3.1, util-promisify-2.1.0, object.getownpropertydescriptors-2.1.0, define-properties-1.1.3, object-keys-1.1.1, es-abstract-1.17.5, es-to-primitive-1.2.1, is-callable-1.1.5, is-date-object-1.0.2, is-symbol-1.0.3, has-symbols-1.0.1, function-bind-1.1.1, has-1.0.3, is-regex-1.0.5, aws-sign2-0.7.0, aws4-1.9.1, caseless-0.12.0,
combined-stream-1.0.8, delayed-stream-1.0.0, extend-3.0.2, forever-agent-0.6.1, form-data-3.0.0, asynckit-0.4.0, mime-types-2.1.27, har-validator-5.1.3, ajv-6.12.2, co-4.6.0, fast-deep-equal-3.1.1, fast-json-stable-stringify-2.1.0, json-schema-traverse-0.4.1, har-schema-2.0.0, http-signature-1.3.4, assert-plus-1.0.0, jsprim-2.0.0, extsprintf-1.4.0, json-schema-0.2.5, verror-1.10.0, sshpk-1.16.1, asn1-0.2.4, bcrypt-pbkdf-1.0.2, tweetnacl-1.0.3, dashdash-1.14.1, ecc-jsbn-0.2.0, jsbn-1.1.0, getpass-0.1.7, is-typedarray-1.0.0, isstream-0.1.2, json-stringify-safe-5.0.1, mime-db-1.44.0, oauth-sign-0.9.0, performance-now-2.1.0, qs-6.9.4, tough-cookie-4.0.0, psl-1.8.0, punycode-2.1.1, tunnel-agent-0.6.0, uuid-8.0.0, sha-3.0.0, sorted-object-2.0.1, sorted-union-stream-3.0.1, stream-iterate-1.2.0, fs-minipass-2.1.0, minizlib-2.1.0, text-table-0.2.0, tiny-relative-date-1.3.0, unique-slug-2.0.2, unpipe-1.0.0, boxen-4.2.0, ansi-align-3.0.0, chalk-4.0.0, cli-boxes-2.2.0, term-size-2.2.0, pseudomap-1.0.2, widest-line-3.1.0, ansi-styles-4.2.1, color-convert-2.0.1, color-name-1.1.4, escape-string-regexp-4.0.0, supports-color-7.1.0, has-flag-4.0.0, configstore-5.0.1, dot-prop-5.2.0, is-obj-2.0.0, make-dir-3.1.0, pify-5.0.0, unique-string-2.0.0, crypto-random-string-3.2.0, xdg-basedir-4.0.0, import-lazy-4.0.0, is-ci-2.0.0, is-installed-globally-0.3.2, global-dirs-2.0.1, is-path-inside-3.0.2, is-npm-5.0.0, latest-version-5.1.0, package-json-6.5.0, got-11.1.3, create-error-class-3.0.2, capture-stack-trace-1.0.1, duplexer3-0.1.4, is-redirect-1.0.0, is-retry-allowed-1.2.0, lowercase-keys-2.0.0, timed-out-5.0.0, unzip-response-3.0.0, url-parse-lax-4.0.0, prepend-http-3.0.1, registry-auth-token-4.1.1, rc-1.2.8, deep-extend-0.6.0, strip-json-comments-3.1.0, registry-url-5.1.0, semver-diff-3.1.1, spdx-correct-3.1.0, spdx-expression-parse-3.0.1, spdx-license-ids-3.0.5, spdx-exceptions-2.3.0, builtins-3.0.1, isexe-2.0.0, errno-0.1.7, prr-1.0.1
        Licenses found in Layer:  Artistic-2.0, ISC, MIT, BSD-2-Clause, Unknown, (WTFPL OR MIT), Apache-2.0, (AFL-2.1 OR BSD-3-Clause), BSD-3-Clause, Unlicense, (BSD-2-Clause OR MIT), (BSD-2-Clause OR MIT OR Apache-2.0), CC0-1.0, CC-BY-3.0
------------------------------------------------

###########################################
# Summary of licenses found in Container: #
###########################################
MIT, GPL-2.0-only, OpenSSL, MPL-2.0 GPL-2.0-or-later, ISC, Zlib, GPL2, MIT BSD GPL2+, BSD, GPL LGPL, Artistic-2.0, BSD-2-Clause, Unknown, (WTFPL OR MIT), Apache-2.0, (AFL-2.1 OR BSD-3-Clause), BSD-3-Clause, Unlicense, (BSD-2-Clause OR MIT), (BSD-2-Clause OR MIT OR Apache-2.0), CC0-1.0, CC-BY-3.0
```

**Comment by rnjudge** [comment]
@nishakm What would you like to do with this PR?

**Comment by nishakm** [comment]
It works. I will merge it.

**Pull request merged**
