### PR TITLE
Replaces image aliases in Dockerfile

### PR DESCRIPTION
**Pull request by mukultaneja**
Replaces image aliases found in FROM instructions
while analyzing Dockerfiles

work towards: #951

Signed-off-by: Mukul Taneja <mtaneja@vmware.com>

### CODE REVIEW

**Comment by mukultaneja** [comment]
@nishakm, @rnjudge, Please review this PR that makes `tern` analyze multi-stage docker files. I know we were talking about entirely different ways to tackle this problem but  I would like to propose this approach as I think this solves our problem without touching any existing classes in the framework. Using this change I could execute multi/single-stage Dockerfile without any errors. 
 
FROM python@sha256:655f71f243ee31eea6774e0b923b990cd400a0689eff049facd2703e57892447
FROM python@sha256:655f71f243ee31eea6774e0b923b990cd400a0689eff049facd2703e57892447

RUN mkdir /install
WORKDIR /install
RUN pip install --no-warn-script-location --prefix=/install \
    tern
FROM python@sha256:655f71f243ee31eea6774e0b923b990cd400a0689eff049facd2703e57892447

RUN echo "deb http://deb.debian.org/debian bullseye main" > /etc/apt/sources.list.d/bullseye.list \
    && echo "Package: *\nPin: release n=bullseye\nPin-Priority: 50" > /etc/apt/preferences.d/bullseye \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
    attr \
    findutils \
    fuse-overlayfs/bullseye \
    fuse3/bullseye \
    git \
    jq \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /install /usr/local
ENTRYPOINT ["tern", "--driver", "fuse"]`

I also tried with the below Dockerfile and it worked fine as well,

FROM node:slim
FROM python:latest

FROM node@sha256:0df270304cb63e22681e2e65d59ece417709cd0db4576074c8bd242041877de9
FROM python@sha256:0813df59b3d73a13fc581fd416d7733a2de6540d7e3f7633a1a9aabf9b201548`

**Comment by mukultaneja** [comment]
@nishakm @rnjudge, Could you please review this PR?

**Comment by nishakm** [comment]
> @nishakm, @rnjudge, Please review this PR that makes `tern` analyze multi-stage docker files. I know we were talking about entirely different ways to tackle this problem but I would like to propose this approach as I think this solves our problem without touching any existing classes in the framework. Using this change I could execute multi/single-stage Dockerfile without any errors.

Thanks for the PR! The change is definitely useful, but it actually addresses a overall issue of parsing multistage docker builds rather than #951. I don't think I have an issue filed for that yet. Could you file one?

**Comment by mukultaneja** [comment]
> > @nishakm, @rnjudge, Please review this PR that makes `tern` analyze multi-stage docker files. I know we were talking about entirely different ways to tackle this problem but I would like to propose this approach as I think this solves our problem without touching any existing classes in the framework. Using this change I could execute multi/single-stage Dockerfile without any errors.
> 
> Thanks for the PR! The change is definitely useful, but it actually addresses a overall issue of parsing multistage docker builds rather than #951. I don't think I have an issue filed for that yet. Could you file one?

Cool! Which other issue you are referring to here?

**Comment by nishakm** [comment]
@mukultaneja This PR doesn't fix #951:
```
2021-05-13 07:01:22,234 - DEBUG - run - Generating locked Dockerfile...
2021-05-13 07:01:22,251 - DEBUG - docker_api - Checking if image "python:3.9-slim-buster" is available on disk...
2021-05-13 07:01:22,253 - DEBUG - docker_api - Image "python:3.9-slim-buster" found
2021-05-13 07:01:22,273 - DEBUG - docker_api - Checking if image "python:3.9-slim-buster" is available on disk...
2021-05-13 07:01:22,275 - DEBUG - docker_api - Attempting to pull image "python:3.9-slim-buster"
2021-05-13 07:01:23,810 - DEBUG - docker_api - Image "python:3.9-slim-buster" downloaded
2021-05-13 07:01:23,823 - DEBUG - docker_api - Checking if image "python:3.9-slim-buster" is available on disk...
2021-05-13 07:01:23,825 - DEBUG - docker_api - Attempting to pull image "python:3.9-slim-buster"
2021-05-13 07:01:25,315 - DEBUG - docker_api - Image "python:3.9-slim-buster" downloaded
2021-05-13 07:01:25,319 - DEBUG - parse - Parsed src_path is --from=builder
```
As explained before, our goal is to get the image string from the `DockerImage` object rather than ask the docker daemon if the image already exists and if not, pulling it.

**Comment by mukultaneja** [comment]
> @mukultaneja This PR doesn't fix #951:
> 
> ```
> 2021-05-13 07:01:22,234 - DEBUG - run - Generating locked Dockerfile...
> 2021-05-13 07:01:22,251 - DEBUG - docker_api - Checking if image "python:3.9-slim-buster" is available on disk...
> 2021-05-13 07:01:22,253 - DEBUG - docker_api - Image "python:3.9-slim-buster" found
> 2021-05-13 07:01:22,273 - DEBUG - docker_api - Checking if image "python:3.9-slim-buster" is available on disk...
> 2021-05-13 07:01:22,275 - DEBUG - docker_api - Attempting to pull image "python:3.9-slim-buster"
> 2021-05-13 07:01:23,810 - DEBUG - docker_api - Image "python:3.9-slim-buster" downloaded
> 2021-05-13 07:01:23,823 - DEBUG - docker_api - Checking if image "python:3.9-slim-buster" is available on disk...
> 2021-05-13 07:01:23,825 - DEBUG - docker_api - Attempting to pull image "python:3.9-slim-buster"
> 2021-05-13 07:01:25,315 - DEBUG - docker_api - Image "python:3.9-slim-buster" downloaded
> 2021-05-13 07:01:25,319 - DEBUG - parse - Parsed src_path is --from=builder
> ```
> 
> As explained before, our goal is to get the image string from the `DockerImage` object rather than ask the docker daemon if the image already exists and if not, pulling it.

@nishakm this actually is happening because we are removing the image right away [here](https://github.com/tern-tools/tern/blob/7fb3d1b06704172627e057bcf8fb2cfea0ef8553/tern/load/docker_api.py#L197).

**Comment by nishakm** [comment]
> > > @nishakm, @rnjudge, Please review this PR that makes `tern` analyze multi-stage docker files. I know we were talking about entirely different ways to tackle this problem but I would like to propose this approach as I think this solves our problem without touching any existing classes in the framework. Using this change I could execute multi/single-stage Dockerfile without any errors.
> > 
> > 
> > Thanks for the PR! The change is definitely useful, but it actually addresses a overall issue of parsing multistage docker builds rather than #951. I don't think I have an issue filed for that yet. Could you file one?
> 
> Cool! Which other issue you are referring to here?

I've created #969 to describe the feature request.

**Comment by mukultaneja** [comment]
> > @mukultaneja This PR doesn't fix #951:
> > ```
> > 2021-05-13 07:01:22,234 - DEBUG - run - Generating locked Dockerfile...
> > 2021-05-13 07:01:22,251 - DEBUG - docker_api - Checking if image "python:3.9-slim-buster" is available on disk...
> > 2021-05-13 07:01:22,253 - DEBUG - docker_api - Image "python:3.9-slim-buster" found
> > 2021-05-13 07:01:22,273 - DEBUG - docker_api - Checking if image "python:3.9-slim-buster" is available on disk...
> > 2021-05-13 07:01:22,275 - DEBUG - docker_api - Attempting to pull image "python:3.9-slim-buster"
> > 2021-05-13 07:01:23,810 - DEBUG - docker_api - Image "python:3.9-slim-buster" downloaded
> > 2021-05-13 07:01:23,823 - DEBUG - docker_api - Checking if image "python:3.9-slim-buster" is available on disk...
> > 2021-05-13 07:01:23,825 - DEBUG - docker_api - Attempting to pull image "python:3.9-slim-buster"
> > 2021-05-13 07:01:25,315 - DEBUG - docker_api - Image "python:3.9-slim-buster" downloaded
> > 2021-05-13 07:01:25,319 - DEBUG - parse - Parsed src_path is --from=builder
> > ```
> > 
> > 
> >   
> >     
> >     
> > 
> >     
> >     
> > 
> >   
> > 
> > 
> > As explained before, our goal is to get the image string from the `DockerImage` object rather than ask the docker daemon if the image already exists and if not, pulling it.
> 
> @nishakm this actually is happening because we are removing the image right away [here](https://github.com/tern-tools/tern/blob/7fb3d1b06704172627e057bcf8fb2cfea0ef8553/tern/load/docker_api.py#L197).

this is the only part that also struck me that is why I wanted your review here

**Comment by nishakm** [comment]
> > @mukultaneja This PR doesn't fix #951:
> > ```
> > 2021-05-13 07:01:22,234 - DEBUG - run - Generating locked Dockerfile...
> > 2021-05-13 07:01:22,251 - DEBUG - docker_api - Checking if image "python:3.9-slim-buster" is available on disk...
> > 2021-05-13 07:01:22,253 - DEBUG - docker_api - Image "python:3.9-slim-buster" found
> > 2021-05-13 07:01:22,273 - DEBUG - docker_api - Checking if image "python:3.9-slim-buster" is available on disk...
> > 2021-05-13 07:01:22,275 - DEBUG - docker_api - Attempting to pull image "python:3.9-slim-buster"
> > 2021-05-13 07:01:23,810 - DEBUG - docker_api - Image "python:3.9-slim-buster" downloaded
> > 2021-05-13 07:01:23,823 - DEBUG - docker_api - Checking if image "python:3.9-slim-buster" is available on disk...
> > 2021-05-13 07:01:23,825 - DEBUG - docker_api - Attempting to pull image "python:3.9-slim-buster"
> > 2021-05-13 07:01:25,315 - DEBUG - docker_api - Image "python:3.9-slim-buster" downloaded
> > 2021-05-13 07:01:25,319 - DEBUG - parse - Parsed src_path is --from=builder
> > ```
> > 
> > 
> >   
> >     
> >     
> > 
> >     
> >     
> > 
> >   
> > 
> > 
> > As explained before, our goal is to get the image string from the `DockerImage` object rather than ask the docker daemon if the image already exists and if not, pulling it.
> 
> @nishakm this actually is happening because we are removing the image right away [here](https://github.com/tern-tools/tern/blob/7fb3d1b06704172627e057bcf8fb2cfea0ef8553/tern/load/docker_api.py#L197).

Yes, we don't want to call `get_docker_image_digest` at this stage.

**Comment by mukultaneja** [comment]
> > > @mukultaneja This PR doesn't fix #951:
> > > ```
> > > 2021-05-13 07:01:22,234 - DEBUG - run - Generating locked Dockerfile...
> > > 2021-05-13 07:01:22,251 - DEBUG - docker_api - Checking if image "python:3.9-slim-buster" is available on disk...
> > > 2021-05-13 07:01:22,253 - DEBUG - docker_api - Image "python:3.9-slim-buster" found
> > > 2021-05-13 07:01:22,273 - DEBUG - docker_api - Checking if image "python:3.9-slim-buster" is available on disk...
> > > 2021-05-13 07:01:22,275 - DEBUG - docker_api - Attempting to pull image "python:3.9-slim-buster"
> > > 2021-05-13 07:01:23,810 - DEBUG - docker_api - Image "python:3.9-slim-buster" downloaded
> > > 2021-05-13 07:01:23,823 - DEBUG - docker_api - Checking if image "python:3.9-slim-buster" is available on disk...
> > > 2021-05-13 07:01:23,825 - DEBUG - docker_api - Attempting to pull image "python:3.9-slim-buster"
> > > 2021-05-13 07:01:25,315 - DEBUG - docker_api - Image "python:3.9-slim-buster" downloaded
> > > 2021-05-13 07:01:25,319 - DEBUG - parse - Parsed src_path is --from=builder
> > > ```
> > > 
> > > 
> > >   
> > >     
> > >     
> > > 
> > >     
> > >     
> > > 
> > >   
> > > 
> > > 
> > > As explained before, our goal is to get the image string from the `DockerImage` object rather than ask the docker daemon if the image already exists and if not, pulling it.
> > 
> > 
> > @nishakm this actually is happening because we are removing the image right away [here](https://github.com/tern-tools/tern/blob/7fb3d1b06704172627e057bcf8fb2cfea0ef8553/tern/load/docker_api.py#L197).
> 
> Yes, we don't want to call `get_docker_image_digest` at this stage.

ok so it means we can remove `get_docker_image_digest` call from `expand_from_images`.. and it will solve the problem

**Comment by nishakm** [comment]
@mukultaneja We've already discussed a good way forward to fix this issue:

`import_image` is not really useful. So what you will need to do is remove `import_str` from `DockerImage` class and set `import_image` with the image string `image@digest_type:digest`

Then in the `lock_dockerfile` function, use `import_str` as the FROM line

**Comment by mukultaneja** [comment]
> @mukultaneja We've already discussed a good way forward to fix this issue:
> 
> `import_image` is not really useful. So what you will need to do is remove `import_str` from `DockerImage` class and set `import_image` with the image string `image@digest_type:digest`
> 
> Then in the `lock_dockerfile` function, use `import_str` as the FROM line

sure @nishakm, as I mentioned I know we discussed but this different idea came to my mind so thought to implement it. Anyway, if you think it won't solve the problem, I will revert back to what we discussed.

**Comment by mukultaneja** [comment]
@nishakm @rnjudge Please review the recent changes I made to this PR. With these changes, I could work with all three Dockerfile formats,
1. Single Stage
2. Multi-Stage
3. Docker file with 2 or more FROM(s)

I would remove the `replace_image_alias` & `find_image_aliases` in the final version of this PR.

**Review by nishakm — CHANGES_REQUESTED** [review]
Hi @mukultaneja, from my testing, this PR successfully fixes #951 but introduces a regression in the "lock" function.

To reproduce:
```
git clone git@github.com:anuvu/zot.git
tern lock zot/Dockerfile
```

Here is what the locked Dockerfile looks like:
```
# ---
# Stage 1: Install certs, build binary, create default config file
# ---
FROM FROM docker.io/golang:1.15.3 AS builderRUN mkdir -p /go/src/github.com/anuvu/zot
WORKDIR /go/src/github.com/anuvu/zot
COPY . . # git project name: zot, HEAD sha: db1744089979c664fd1a3ac62281a4bbed5ffa93, project url(s): https://github.com/anuvu/zot
RUN CGO_ENABLED=0 make clean binary











RUN echo '{\n\
    "storage": {\n\
        "rootDirectory": "/var/lib/registry"\n\
    },\n\
    "http": {\n\
        "address": "0.0.0.0",\n\
        "port": "5000"\n\
    },\n\
    "log": {\n\
        "level": "debug"\n\
    }\n\
}\n' > config.json && cat config.json

# ---
# Stage 2: Final image with nothing but certs, binary, and default config file
# ---
FROM FROM docker.io/golang:1.15.3 AS builderCOPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt # git project name: zot, HEAD sha: db1744089979c664fd1a3ac62281a4bbed5ffa93, project url(s): https://github.com/anuvu/zot
COPY --from=builder /go/src/github.com/anuvu/zot/bin/zot /zot # git project name: zot, HEAD sha: db1744089979c664fd1a3ac62281a4bbed5ffa93, project url(s): https://github.com/anuvu/zot
COPY --from=builder /go/src/github.com/anuvu/zot/config.json /etc/zot/config.json # git project name: zot, HEAD sha: db1744089979c664fd1a3ac62281a4bbed5ffa93, project url(s): https://github.com/anuvu/zot
ENTRYPOINT ["/zot"]
EXPOSE 5000
VOLUME ["/var/lib/registry"]
CMD ["serve", "/etc/zot/config.json"]
```

The only issue is that the FROM line repeats `FROM` twice and then removes the newline after that for both stages and the image tag is not replaced with its digest. At this point, more work needs to be done to deal with the `COPY --from=builder` situation. I'll take a look at your changes and see what you can fix.

**Comment by mukultaneja** [comment]
@nishakm I addressed two of the issues you mentioned in my recent push,
1. Repeated `FROM`
2. Missing new lines character.

I also looked into why `the image tag is not replaced with its digest` and it is because the `import_str` is being set [here](https://github.com/tern-tools/tern/blob/main/tern/analyze/default/dockerfile/run.py#L78) for the docker file which you used. My changes check that if the `import_str` is not being set after this above step then it would go ahead and set properly.

**Comment by mukultaneja** [comment]
@nishakm, are the changes looking good?

**Review by nishakm — CHANGES_REQUESTED** [review]
All changes look good and work! Thank you! One small change: Could you expand on your commit message?

<subject>

<why the change is needed>

<list all the changes made and for what reason>

Fixes:

**Comment by mukultaneja** [comment]
> All changes look good and work! Thank you! One small change: Could you expand on your commit message?
> 
> ```
> <subject>
> 
> <why the change is needed>
> 
> <list all the changes made and for what reason>
> 
> Fixes: #....
> ```

@nishakm Done!

**Review by nishakm — APPROVED** [review]

**Pull request merged**
