### PR TITLE
SPDXVersion is now SPDX-2.2

### PR DESCRIPTION
**Pull request by vargenau**
Update documentation: currently, tern creates SPDXVersion with value SPDX-2.2.

### CODE REVIEW

**Comment by vargenau** [comment]
Hi Rose,

I have updated the commit message.
I hope I have done it correctly.

Best regards,

Marc-Etienne

**Comment by vargenau** [comment]
Hi Rose,

Are you now able to pull my commits?

Best regards,

Marc-Etienne

From: Vargenau, Marc-Etienne (Nokia - FR/Paris-Saclay) ***@***.***>
Sent: Friday, April 1, 2022 12:29 PM
To: tern-tools/tern ***@***.***>; tern-tools/tern ***@***.***>
Cc: Mention ***@***.***>; Vargenau, Marc-Etienne (Nokia - FR/Paris-Saclay) ***@***.***>
Subject: RE: [tern-tools/tern] SPDXVersion is now SPDX-2.2 (PR #1144)

Hi Rose,

I have updated the commit message.
I hope I have done it correctly.

Best regards,

Marc-Etienne

**Comment by rnjudge** [comment]
Hi @vargenau- your actual code change looks good but you still have many of the same commit attached to this PR. Want me to take this over and get it merged?

**Comment by vargenau** [comment]
Hi Rose,

Yes, please merge. Sorry about the multiple commits.

**Comment by rnjudge** [comment]
Closing in lieu of https://github.com/tern-tools/tern/pull/1152.

**Pull request closed without merging**
