### PR TITLE
Remove circleci from running on pull requests

### LINKED ISSUE #735: Remove circleci from running on pull requests
**Problem Statement**
PR https://github.com/tern-tools/tern/pull/734 is currently open to add an OCI image class to Tern in order to support the analysis of various OCI client images. In order to test the functionality of this analysis, we will need to use [skopeo](https://github.com/containers/skopeo) to convert images pulled from Dockerhub. Skopeo, however, [requires at least Ubuntu 1804](https://github.com/containers/skopeo/blob/master/install.md) to be installed on the CI test machine. Currently, CircleCI's machine executor for the tests only supports Ubuntu 1604 with no plans to support 1804 in the near future. Therefore, we need to remove circleci from running on pull requests and switch to GitHub Actions.

**Describe the Proposal**
Remove the `.circleci/config.yml` file and possibly the app associated with it on GitHub.

### PR DESCRIPTION
**Pull request by rnjudge**
Tern is planning to add an OCI image class in order to support the
analysis of various OCI image client images. In order to test the
functionality of this analysis, we will use the skopeo tool to convert
images pulled from Dockerhub. Skopeo requires Ubuntu 1804 for
installation. However, Ubuntu 1604 is the latest available Linux image
for CircleCI machine execturs. Therefore, we will switch to GitHub
Actions to run the CI tests for pull requests, as GHA supports Ubuntu
1804 for their test machines.

Resolves #735

Signed-off-by: Rose Judge <rjudge@vmware.com>

### CODE REVIEW

**Comment by rnjudge** [comment]
@nishakm If you approve of this PR, I can remove the circleci app from running before we merge this.

**Comment by nishakm** [comment]
In the commit message, `s/execturs/executors`. I will miss the different test divisions that CircleCI has. Can we configure the same thing with GHA?

**Comment by rnjudge** [comment]
> In the commit message, `s/execturs/executors`. I will miss the different test divisions that CircleCI has. Can we configure the same thing with GHA?

Yes, we can.. that is next on my list :)

**Comment by nishakm** [comment]
Alright! Merging 🤞

**Pull request merged**
