### PR TITLE
Don't set digest type for raw image tarballs

### LINKED ISSUE #719: tern 2.1.0 -w *.tar error
(tven) [root@localhost hf]# tern --version
Tern version 2.1.0
   python version = 3.6.8 (default, Apr  2 2020, 13:34:55)
(tven) [root@localhost hf]#tern report -w vru-cudr-sys-mp.tar -x cve_bin_tool
2020-06-04 11:55:06,567 - DEBUG - __main__ - Starting...
2020-06-04 11:55:06,570 - DEBUG - run - Setting up...
2020-06-04 11:55:06,572 - DEBUG - container - Checking if image "vru-cudr-sys-mp.tar" is available on disk...
Traceback (most recent call last):
  File "/home/hf/tven/bin/tern", line 8, in <module>
    sys.exit(main())
  File "/home/hf/tven/lib64/python3.6/site-packages/tern/__main__.py", line 201, in main
    do_main(args)
  File "/home/hf/tven/lib64/python3.6/site-packages/tern/__main__.py", line 113, in do_main
    run.execute_docker_image(args)
  File "/home/hf/tven/lib64/python3.6/site-packages/tern/analyze/docker/run.py", line 83, in execute_docker_image
    full_image = report.load_full_image(image_string)
  File "/home/hf/tven/lib64/python3.6/site-packages/tern/report/report.py", line 113, in load_full_image
    test_image = DockerImage(image_tag_string)
  File "/home/hf/tven/lib64/python3.6/site-packages/tern/classes/docker_image.py", line 42, in __init__
    docker_image = container.check_image(self.__repotag)
  File "/home/hf/tven/lib64/python3.6/site-packages/tern/analyze/docker/container.py", line 80, in check_image
    image = client.images.get(image_tag_string)
AttributeError: 'NoneType' object has no attribute 'images'

### PR DESCRIPTION
**Pull request by rnjudge**
This commit resolves a regression that happens when Tern attempts to set
the checksum for Docker images that are given in raw form. If the image
provided is in raw image form, we cannot pull the digest of the image
and should skip setting the checksum (in this case, the checksum will
default to a blank string).

This commit also adds a raw image tarball and tests to our CI that will
test running Tern on a raw image tarball so we can try to catch issues
like this in the future.

Resolves #719

Signed-off-by: Rose Judge <rjudge@vmware.com>

### CODE REVIEW

**Comment by rnjudge** [comment]
@nishakm Fixed the typo :)

**Comment by nishakm** [comment]
@rnjudge did you mean to commit a tarball? `ci/photon30.tar.gz`

**Comment by nishakm** [comment]
> @nishakm Yes. It is used for the ci tests that I added.

Any chance of doing a `docker pull photon@sha256:... && docker save > tarball.tar` out of band to create this tarball? The reason is that git doesn't work very well with binary blobs (the diffs take up a lot of space).

**Comment by rnjudge** [comment]
Ack, I totally screwed up my commits. Let me fix.

**Pull request closed without merging**
